const messages = {
    en: {
      message: {
        menuHome:"Home",
        menuWhitePaper: 'White Paper',
        menuSolution:"Solution",
        menuTeam:"Team",
        menuPartner:"Partner",
        menuContactUs:"Contact Us",
        newsTitle:"News",
        languangeEn:"English",
        languangeCn:"Chinese",
        aboutUs:"ABOUT US",
        conpany:"AN USA BASED BIOPHARMACEUTICAL TECHNOLOGY COMPANY",
        originator:"As the initiator of DLucky Chain , we mainly focus on the  industrial application and ecological implementation in  the biomedicine field. We made a strategic investment in a pharmaceutical company in Qingdao China, and took it as the first application scenario for blockchain-based medical traceability.On this basis, we also started the R&D of blockchain traceability technology in combination with related medical production equipments and process.",
        des:"We made a strategic investment in a pharmaceutical company in Qingdao China, and took it as the first application scenario for blockchain-based medical traceability.On this basis, we also started the R&D of blockchain traceability technology in combination with related medical production equipments and process.",
        projectIntroduction:"PROJECT <br> INTRODUCTION",
        introduction1:"DLucky Chain is a global project initiated by DOUBLE LUCKY BIOPHARMACEUTICAL LTD, focusing on the pharmaceutical industry. It is atraceability application developed based on EOS technical standards, and USES the irreversible distributed ledger record feature of block Chain to solve the problems of information traceability, anti-foraging and authenticity in the process of raw material warehousing production and consumption in the industry.",
        introduction2:"The project combines the hardware and software required in the anti-counterfeiting process with block chain technology to create an application protocol for the implementation of block chain traceability technology. The agreement focuses on medicine traceability and anti-counterfeiting. In the process of verification record, chain storage and anti-counterfeiting tracing of the traceability data, a series of specifications and constraints are designed for the process of data inspection, storage and tracing through technical agreements between hardware and software.",
        downloadWhitePaper:"Download White Paper",
        englishVersion:"English Version",
        chineseVersion:"中文版",
        solution:"SOLUTION：DLUCKY CHAIN",
        softwareLayer:"Software Layer",
        softwareLayerIntroduction:"At the software level, we provide service functions including protocols, interfaces, validation, interaction, also support function extension.",
        hardwareLaver:"Hardware Layer",
        hardwareLaverIntroduction:" The hardware level mainly includes auxiliary nodes, light wallet servers, DEye, DCode, etc",
        overallSolution:"Combined with block chain technology, the unique design of hardware and software in the process of anti-counterfeiting will create.",
        applicationScenarios:"THE FIRST APPLICATION<br>SCENARIO OF DLUCKY CHAIN",
        rawmaterial:"Raw Material",
        treatmen:"Treatmen",
        sterilization:"Sterilization",
        purification:"D-grade \n Purification",
        internal:"Internal \n packaging",
        outSide:"Outside \n packaging",
        finalProduct:"Final product",
        rawmaterial:"Raw Material",
        DEye:"D-Eye",
        DCode:"D-Code",
        dluckyChain:"DLUCKY CHAIN",
        DTag:"D-Tag",
        users:"Users",
        inputdData:"Input data",
        application:"Application code and query \n code Cache to DCode",
        encoding:"Encoding (Printing)",
        uploadData:"Upload data",
        returnCode:"Return application code \n And query code",
        ourTeam:"OUR TEAM",
        ceo:"Major in Pharmaceutical Chemistry.Beijing University of Traditional Chinese Medicine MBA from Renmin University of China.Zhejiang Guoguang Biopharmaceutical co LTD.General Manager of Health Group Industry Corporation",
        coo:"Renmin University of China Management MBA.Hubei Xianning Medical College Pharmacy Major Qingdao Sanli Chemical Technology Co, LTD Inspection Engineer",
        cto:"Bachelor of Information Technology and Data Analytics, University of South Australia, CTO of DLucky Pharmaceutical, R&D at Digital Stock Exchange, Founder at Syndicate Group",
        cmo:"Shandong University, major in Biological Engineering Dessert Zhendong Pharmaceutical Co, Ltd Sales director for multiple companies",
        cio:"Heilongjiang University of Traditional Chinese Medicine, major in Traditional Chinese Medicine Kang Yuan Pharmaceutical Research Institute Deputy Director We completed several major science technology projects",
        consultants:"CONSULTANTS",
        taoran:"Member of the United Nations International Academy of Ecological and Life Safety Specialist of Army General Hospital Deputy Director, Department of Clinical Psychology, Capital Medical University Director of Beijing Shijian United Medical",
        taokai:"State Experts in Traditional Chinese Medicine Chief Physician of Pulmonary Department,Affiliated Hospital of Shandong University of Traditional Chinese Medicine Professor, Department of Internal Medicine, Shandong University of Traditional Chinese Medicine",
        partnterCompanies:"PARTNER  <br> COMPANIES",
        jiafucheng:"Founded in May 2004, is a professional global asset management institution with the main business: asset management, wealth management and investment banking.",
        qingchenziben:"Morning Capital concentrates on the traditional investment banking business, includesb listing, financing, merging and OTC market etc.",
        zhongxiangjituan:'Founded in 1998, the company has set foot in real estate, finance, culture, biologica medicine, big health and other fields. Adhering to the business philosophy of excellence, innovation, efficiency and pragmatism", the company is famous for innovating finance, innovating real estate, creating a new model of real estate.',
        haichuanghui:"Hai Chuanghui (HCH), an entrepreneurial platform for Haier Group to transform from product manufacturing to maker incubation, accelerates and enables small and medium-sized enterprises in reliance upon Haier Group’s industrial resources and HCH’s open ecosystem resources, to accelerate growth and reduce failure risks of entrepreneurs. One-stop acceleration services, including acceleration through industry resources, investment, financing, entrepreneurship training and makerspace etc., are provided for entrepreneurs",
        genyuanziben:"Founded in 2011, the company s business scope includes real estate development and management; Property management; Cleaning service, etc",
        roadMap:"ROAD MAP",
        month:'JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEPT,OCT,NOV,DEC',
        y20177:"Project set up, starts to plan, and carry on the development strategy.",
        y201711:"The construction of the applied scenario base project pass the local development and reform bureau",
        y20180:"Obtains the construction land planning license",
        y20183:"The application scene base has officially started construction",
        y20189:"The construction of the phase i completed, and Double Lucky officially acquired the base as the first pilot of the drug traceability project DLucky",
        y201810:"DLucky project was initiated to develop traceability technologies",
        y201811:"Identify the technical framework for traceability and document development",
        y20190:"The DLucky Chain entered the development stage and started build the main network",
        y20191:"Start the r&d of traceability technology, production equipment and production line",
        y20193:"DLucky Chain network layer completed, the establishment and debugging of the network, and phase ii of the base completed",
        y20194:"DLucky Chain Data layer design completed, access debugging network",
        y20195:"DEye hardware developed, connected to the debugging network",
        y20197:"DLucky Chain The consensus layer completes PoA embedding and deploys the test superrights node",
        y20199:"DLucky Chain Completed the design of incentive mechanism and combined with DEye testing and debugging",
        y201910:"The phase iii of the scene base completed, all production equipment installed. Dcode hardware development completed",
        y201911:"Complete the main hardware equipment, access to production equipment debugging",
        y20200:"DLucky Chain main network completed and test network put online",
        y20202:"DLucky Chain Hardware development completed, with production equipment and production line testing",
        y20203:"Pass the GMP",
        y20204:"The software and hardware all completed, the test network is connected to carry out the co-debugging",
        y20206:"The DLucky Chain officially launched, and put into use",
        futureProspect:"FUTURE PROSPECT",
        futureProspectContect1:"Provides traceability data for pharmaceutical \n practitioners and consumers in areas such as the use of \n special drugs and the disposal of expired drugs",
        futureProspectContect2:"Traceability technology extends to health \n food, general food, special medicine food,\n Chinese medicine pieces, formula granules,\n medical devices and other product types",
        futureProspectContect3:"Cooperate with more production and commercial enterprises, \n connect product and technical data through terminals, break \n information islands, create all-round traceable data, andprovide basis \n for government departments and market supervision",
        futureProspectContect4:"Establish an international traceability brand \n in the global pharmaceutical industry",
        futureProspectContect5:"Set up industry benchmark and establishing \n a safe and perfect pharmaceutical industry \n environment for China's pharmaceutical  \n market",
        contactUs:"CONTACT US",
        community:" JOIN OUR COMMUNITY",
        email:" SEND US EMAIL",
        information:" INFORMATION",
        address:"Address",
        phone:"Phone",
        customerService:"CUSTOMER SERVICE",
        news:"NEWS",
        footInfo:"You can find more details about Double Lucky in our terms of use and privacy policy.",
        copyright:"Copyright © 2019 DOUBLE LUCKY BIOPHARMACEUTICAL LTD"
      }
    },
    cn: {
      message: {
        menuHome:"首页",
        menuWhitePaper: '白皮书',
        menuSolution:"解决方案",
        menuTeam:"团队介绍",
        menuPartner:"合作机构",
        menuContactUs:"联系我们",
        newsTitle:"新闻资讯",
        languangeEn:"English",
        languangeCn:"中文",
        aboutUs:"关于我们",
        conpany:"一家美国生物制药科技有限公司",
        originator:"DLucky Chain项目的发起者, 我们主要致力于生物医药领域的行业应用和生态落地，2018年10月对中国青岛一家制药公司进行战略投资，并将其作为医疗行业区块链溯源生态的第一应用场景。在此基础上，启动区块链溯源技术与生产设备、生产线相结合的研发。" ,
        des:"Double Lucky与该药企对医疗行业溯源的需求一致，进行战略投资后并将药企作为区块链医疗溯源技术的第一应用场景，启动区块链溯源技术与生产设备、生产线相结合的研发。" ,
        projectIntroduction:"项目介绍",
        introduction1:"DLucky chain是由 DOUBLE LUCKY BIOPHARMACEUTICAL LTD发起的一个全球化项目,专注于医药行业,基于EOS技术标准开发的溯源应用,利用区块链不可逆的分布式账簿记录特性,解决行业内从原材料入库,生产至销售消费过程中的信息溯源、防伪验真等难题。",
        introduction2:"项目通过防伪过程所需的硬件及软件分别结合区块链技术，打造区块链溯源技术落地的应用协议。协议专注于医药溯源与防伪，在溯源数据的验证记录、链上存储、防伪追溯的过程中，通过硬件和软件间的技术约定，对数据的检验存储、查询追溯等流程设计了一系列的规范和约束。",
        downloadWhitePaper:"白皮书下载",
        englishVersion:"English Version",
        chineseVersion:"中文版",
        solution:"解决方案：DLUCKY CHAIN",
        softwareLayer:"软件层",
        softwareLayerIntroduction:"在软件层面,我们提供包含协议、接口、验证、交互等基础的服务功能,并支持功能延伸和扩展。",
        hardwareLaver:"硬件层",
        hardwareLaverIntroduction:"在硬件层面,主要包含辅助节点、轻钱包服务器、DEye、DCode等。",
        overallSolution:"对防伪过程中的硬件及软件结合区块链技术进行独特设计,打造真正意义上的医药行业防伪溯源落地应用。",
        applicationScenarios:"DLUCKY CHAIN 第一应用场景",
        rawmaterial:"原材料",
        treatmen:"处理",
        sterilization:"灭菌",
        purification:"D级净化",
        internal:"内包装",
        outSide:"外包装",
        finalProduct:"成品",
        DEye:"D-Eye",
        DCode:"D-Code",
        dluckyChain:"DLUCKY CHAIN 主网络",
        DTag:"D-Tag",
        users:"用户",
        inputdData:"录入数据",
        application:"将应用码和查询码 \n 缓存至DCode",
        encoding:"赋码（打印）",
        uploadData:"上传数据",
        returnCode:"返回应用码和查询码",
        ourTeam:"核心团队",
        ceo:"北京中医药大学药物化学专业、中国人民大学工商管理硕士,工程师职称、山东天达药业有限公司副总经理、山东圣邦(太阳石)医药有限公司董事副总经理、浙江国光生物制药有限公司总经理",
        coo:"中国人民大学管理学MBA、湖北咸宁医学院药学专业,中级工程师职称、青岛三力化工技术有限公司检验工程师、苏州华仁太医药业副总经理、青岛华仁太医药业质管部长、生产部长、成本中心副总经理、总工程师",
        cto:"DLucky项目技术总监、数字证券交易所开发者、辛迪加集团创始人",
        cmo:"山西振东制药股份有限公司销售总监、沈阳红药集团制药股份有限公司销售总经理、山东东阿阿胶股份有限公司销售总监、提出“三年五亿”销售工程战略,编写《东阿阿胶排他性工作项目指导书》,提出“三个聚焦”营销战略,推动“3+3+3+2”战术落地",
        cio:"黑龙江中医药大学中药学专业、江苏康缘药业中药及天然药物新药硏究所副所长、安徽济人药业科研部经理、国家重点实验室一中药注射剂除杂技术研究、中药注射液无菌保障技术研究、组织完成多个“重大新药创制”科技重大专项",
        consultants:"顾问团队",
        taoran:"联合国国际生态生命安全科学院院士、陆军总医院专家组专家、首都医科大学临床心理学系副主任、北京世健联合医学科学研究院院长",
        taokai:"国家名老中医药专家、现任山东中医药大学附属医院肺病科主任医师、山东中医药大学内科教研室教授、山东中西医结合学会呼吸病专业委员会主任委员",
        partnterCompanies:"合作机构",
        jiafucheng:"成立于2004年5月,是以资产管理、财富管理、投资银行为主业的全球资产管理专业机构。",
        qingchenziben:"清晨资本是国内知名的专业基金管理、股权投资机构,2014年荣获青岛市年度经济成就奖最具创新力企业”,是青岛市2015年度的“十佳投资机构”。公司专注投资新能源、新材料、生物医药、现代服努、节能环保、海洋经济、互联网等持续高成长的朝阳产业。",
        zhongxiangjituan:'创立于1998年,涉足房地产、金融、文化、生物医药、大健康等多个领域,企业秉承“卓越、创新、高效、务实”的经营理念,以“创新金融、创新地产、打造地产新模式”而著称。',
        haichuanghui:"海创汇是海尔集团由制造产品向孵化创客转型的创业平台，依托海尔集团大企业产业资源及海创汇开放的生态资源为中小企业加速赋能，让创业者加速成长，减少失败。我们为创业者提供产业资源加速、投融资、创业培训、创客空间等一站式加速服务。",
        genyuanziben:"成立于2011年,公司经营范围包括房地产开发与经营;物业管理;保洁服务等。",
        roadMap:"路线图",
        month:'1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月',
        y20177:"应用场景基地正式立项，启动项目规划，并进行发展战略部署",
        y201711:"应用场景基地项目建设在当地发展和改革局完成项目备案",
        y20180:"应用场景基地获得建设用地规划许可证",
        y20183:"应用场景基地正式开始施工建设",
        y20189:"应用场景基地一期厂房建设完成，Double Lucky公司正式收购基地，作为药品溯源项目DLucky的首个试点",
        y201810:"DLucky项目启动以溯源技术研发",
        y201811:"确定溯源技术架构，编制开发文档",
        y20190:"DLucky Chain项目正式进入开发阶段，启动主网络开发",
        y20191:"启动溯源技术搭配生产设备和生产线研发",
        y20193:"DLucky Chain 网络层开发完成，组建调试网络，应用场景基地二期建筑完工",
        y20194:"DLucky Chain数据层设计完成，接入调试网络调试",
        y20195:"DEye硬件研发完成，将接入调试网络调试",
        y20197:"DLucky Chain共识层完成POA嵌入，部署测试用超级权益节点",
        y20199:"DLucky Chain激励机制设计完成，结合DEye测试调试",
        y201910:"应用场景基地三期建筑全部完工，同时生产全线设备安装到位，Dcode硬件研发完成，接入调试网络调试",
        y201911:"主要硬件设备研发完成，接入生产设备调试",
        y20200:"DLucky Chain主网络组合完成，上线测试网络",
        y20202:"DLucky Chain硬件研发完毕，搭配生产设备和生产线测试",
        y20203:"正式通过药品生产质量管理规范认证（GOOD MANUFACTURING PRACTICE 既GMP认证）",
        y20204:"DLucky Chain项目软硬件开发完毕，接入测试网络进行软硬件联调测试",
        y20206:"DLucky Chain正式上线，溯源技术正式投入使用，药品正式进入生产",
        futureProspect:"未来展望",
        futureProspectContect1:"布局在特殊药品的用途、过期药品处理等领域，为 \n 医药从业者和消费者提供全程的溯源数据",
        futureProspectContect2:"溯源技术延伸至保健食品、普通 \n 食品、特医食品、中药饮片、配方颗 \n 粒、医疗器械等多种产品类型",
        futureProspectContect3:"与更多生产企业、商业企业进行合作，通过终端串联接 \n 入各类型产品及技术资料等，打破行业信息孤岛，打造 \n 全方位溯源数据，为政府部门和市场监管供依据",
        futureProspectContect4:"采用国际通行的行业标准的认证规范，\n 树立属于中国医药行业的民族品牌",
        futureProspectContect5:"从自身做起，树立行业标杆，为中国 \n 医药市场建立一个安全、完善的医药行业 \n 环境。",
        contactUs:"联络我们",
        community:" 加入我们的社群",
        email:" 给我们发邮件",
        information:" 公司信息",
        address:"地址: ",
        phone:"电话: ",
        customerService:"客服助手",
        news:"新闻资讯",
        footInfo:"您可以在我们的使用条款和隐私政策中找到有关Double Lucky网站的更多详细信息",
        copyright:"版权所有 © 2019 DOUBLE LUCKY BIOPHARMACEUTICAL LTD"
      }
    }
  }
  export  default messages;